### PR TITLE
Contentdimensionindex

### PR DESCRIPTION
**Pull request by chrschw**
I changed the indexing to separate each language into another Index. 

Reason: Suggest controller results are not separated by language

### CODE REVIEW

**Comment by dfeyer** [comment]
I think this is not the responsability of the SearchPlugin, see my PR for the Adapter package:
https://github.com/Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor/pull/227

**Comment by kdambekalns** [comment]
Thanks for your contribution!

But… This is to be solved based on Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor#227. Also it looks incomplete - why would changing the `SuggestController` magically make this work?

Feel free to reopen and further work on this, if you like and/or still need it.

**Comment by chrschw** [comment]
This pullrequest is outdated. Beacause dfeyer already added this feature. Sorry i did not closed this PR.

(This PR was just a part depending on a the Flowpack.ElasticSearch.ContentRepositoryAdapter PR: https://github.com/Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor/pull/216)

**Comment by kdambekalns** [comment]
Ok, thanks for getting back to it!

**Pull request closed without merging**
