### PR TITLE
BUGFIX: Make completions/suggestions work with ES 5.x

### PR DESCRIPTION
**Pull request by kdambekalns**
This would remove the need for https://github.com/Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor/pull/284

### CODE REVIEW

**Comment by kdambekalns** [comment]
Could/should this be done for 3.1?

**Comment by JosefBredereck** [comment]
What is the current status in that case?

**Comment by grizooo** [comment]
Hi, i tried to make nodeindex:build with ES 5.3 and got these errors:

Mapping definitions for [xxx] has unsupported parameters ...

this is the only NodeTypes.Mixin.yaml which works:

<pre>
'Flowpack.SearchPlugin:SuggestableMixin':
  abstract: true
  properties:
    '__suggestions':
      search:
        elasticSearchMapping:
          type: completion
        indexing: "${Flowpack.SearchPlugin.Suggestion.build(q(node).property('title') ? q(node).property('title') : '', q(node).is('[instanceof Neos.Neos:Document]') ? node.identifier : q(node).parents('[instanceof Neos.Neos:Document]').get(0).identifier, {nodeIdentifier: node.identifier}, 20)}"

'Flowpack.SearchPlugin:AutocompletableMixin':
  abstract: true
  properties:
    '__completion':
      search:
        elasticSearchMapping:
          type: string
        indexing: "${String.stripTags(q(node).property('title'))}"


</pre>

Usupported parameters:

payloads, context in Flowpack.SearchPlugin:SuggestableMixin
analyzer in Flowpack.SearchPlugin:AutocompletableMixin

**Comment by kdambekalns** [comment]
@daniellienert I lost trrack of the current status, is this something that still needs to be fixed? Or can this PR be thrown away by now?

**Comment by daniellienert** [comment]
I am pretty sure it is. Also on my list actually, but didn't find the time yet

**Pull request merged**
