### PR TITLE
!!! TASK: Require manual configuration of autocomplete

### PR DESCRIPTION
**Pull request by kdambekalns**
See #38 for the problem this "solves" (for the time being.)

### CODE REVIEW

**Comment by kitsunet** [comment]
It's still a bc change, IMHO we must fix it (eg. by reverting and releasing it as major version)

**Comment by daniellienert** [comment]
I suggest remove the autocomplete configuration from the settings and only mention in the radme, how to enable this feature for your specific index name.

**Comment by kdambekalns** [comment]
Well, then we need to move the settings _and_ the needed nodetype changes (adding the suggestable mixin) to the readme…

**Comment by DrillSergeant** [comment]
I also stumbled into problems with searchPlugin when using it together with the one-index-per-dimensioncombination strategy (https://github.com/Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor/pull/245)

My problem was the missing field **__dimensionCombinationHash** which is expected by the SuggestionMixin. As a result my document-nodes were indexed, but almost emtpy. I solved it by not using the mixin:
```
'Neos.Neos:Document':
  superTypes:
    'Flowpack.SearchPlugin:SuggestableMixin': FALSE
```

Took a while to figure it out. I will comment this in the mentioned pull-request, but not having the mixin applied by default would prevent others from that problem.

**Comment by kdambekalns** [comment]
Ping…

**Pull request merged**
